# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/bulat/Рабочий стол/gitH/myWeather/designWea.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(316, 367)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_1 = QtWidgets.QVBoxLayout()
        self.verticalLayout_1.setObjectName("verticalLayout_1")
        self.todayIs = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Lato Hairline")
        font.setPointSize(14)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.todayIs.setFont(font)
        self.todayIs.setAlignment(QtCore.Qt.AlignCenter)
        self.todayIs.setObjectName("todayIs")
        self.verticalLayout_1.addWidget(self.todayIs)
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Lato Hairline")
        font.setPointSize(25)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_1.addWidget(self.label)
        self.weathIs = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Oxygen-Sans")
        font.setPointSize(10)
        font.setItalic(False)
        self.weathIs.setFont(font)
        self.weathIs.setAlignment(QtCore.Qt.AlignCenter)
        self.weathIs.setObjectName("weathIs")
        self.verticalLayout_1.addWidget(self.weathIs)
        self.TempIc = QtWidgets.QLabel(self.centralwidget)
        self.TempIc.setMinimumSize(QtCore.QSize(64, 64))
        self.TempIc.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.TempIc.setAlignment(QtCore.Qt.AlignCenter)
        self.TempIc.setObjectName("TempIc")
        self.verticalLayout_1.addWidget(self.TempIc)
        self.Temp = QtWidgets.QLabel(self.centralwidget)
        self.Temp.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Lato Thin")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.Temp.setFont(font)
        self.Temp.setAlignment(QtCore.Qt.AlignCenter)
        self.Temp.setObjectName("Temp")
        self.verticalLayout_1.addWidget(self.Temp)
        self.verticalLayout.addLayout(self.verticalLayout_1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.inRoom = QtWidgets.QLabel(self.centralwidget)
        self.inRoom.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.inRoom.setObjectName("inRoom")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.inRoom)
        self.temperatureLabel = QtWidgets.QLabel(self.centralwidget)
        self.temperatureLabel.setText("")
        self.temperatureLabel.setObjectName("temperatureLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.temperatureLabel)
        self.hum = QtWidgets.QLabel(self.centralwidget)
        self.hum.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.hum.setObjectName("hum")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.hum)
        self.humidityLabel = QtWidgets.QLabel(self.centralwidget)
        self.humidityLabel.setText("")
        self.humidityLabel.setObjectName("humidityLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.humidityLabel)
        self.wind = QtWidgets.QLabel(self.centralwidget)
        self.wind.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.wind.setObjectName("wind")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.wind)
        self.windLabel = QtWidgets.QLabel(self.centralwidget)
        self.windLabel.setText("")
        self.windLabel.setObjectName("windLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.windLabel)
        self.gridLayout.addLayout(self.formLayout, 1, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.verticalLayout_2.setContentsMargins(-1, 10, -1, 6)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../.designer/weather/images/arrow-circle-225.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_2.addWidget(self.pushButton_2)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        self.horizontalLayout.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Weather"))
        self.todayIs.setText(_translate("MainWindow", "Понедельник 26 ноября"))
        self.label.setText(_translate("MainWindow", "TextLabel"))
        self.weathIs.setText(_translate("MainWindow", "25 C, Ясно"))
        self.TempIc.setText(_translate("MainWindow", "ICON"))
        self.Temp.setText(_translate("MainWindow", "TEMP"))
        self.inRoom.setText(_translate("MainWindow", "В комнате:"))
        self.hum.setText(_translate("MainWindow", "Влажность:"))
        self.wind.setText(_translate("MainWindow", "Ветер:"))

